name: Amakomaya
description: A new Flutter project.

publish_to: "none"

version: 7.0.3+45
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  #routing
  analyzer: ^6.2.0
  auto_route: ^3.2.4
  bot_toast: ^4.0.4
  dio: ^5.3.0
  wakelock: ^0.6.2
  wakelock_windows: ^0.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^3.0.0-alpha.5
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  shimmer: ^3.0.0
  package_info_plus: ^4.1.0

  video_player: ^2.7.0
  scrollable_positioned_list: ^0.3.8
  audioplayers: ^1.0.1
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.2.0
  permission_handler: ^10.4.3
  another_flushbar: ^1.12.30
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^4.2.4
  animated_text_kit: ^4.2.2
  qr_code_scanner: ^1.0.1
  nepali_date_picker: ^5.3.1
  eva_icons_flutter: ^3.1.0
  qr_flutter: ^4.1.0
  path_provider: 2.0.9
  get_it: ^7.6.0
  device_info_plus: ^9.0.3
  image_gallery_saver: ^2.0.3
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.3
  easy_localization: ^3.0.2
  hive_generator: ^2.0.1
  hydrated_bloc: ^9.1.2
  uuid: ^3.0.1
  flick_video_player: ^0.5.0
  flutter_linkify: ^6.0.0
    #for call
  url_launcher: ^6.1.12

  flutter_phone_direct_caller: ^2.1.1
dependency_overrides:
  win32: ^5.0.0
#launcher icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/profile.png"

  cupertino_icons: ^1.0.5
  #for svgs
  flutter_svg: ^2.0.7
  #BLOC(State Management)
  flutter_bloc: ^8.1.3
  #dependency injection

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/siren.mp3
    - assets/icons/
    - assets/fonts/
    - assets/images/splash/
    - assets/images/logo/
    - assets/images/logo/drawer/
    - assets/l10n/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
