name: aamako_maya
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  #routing
  analyzer: ^4.1.0
  auto_route: ^3.2.4
  bot_toast: ^4.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^3.0.0-alpha.5
  flutter_launcher_icons: ^0.9.2
  # flutter_native_splash: ^2.1.6
  #caching
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  chewie:
  video_player:
  scrollable_positioned_list: ^0.3.1
  audioplayers: ^1.0.1
  visibility_detector: ^0.2.2
  shared_preferences: ^2.0.15

  animated_text_kit: ^4.2.1
  qr_code_scanner: ^0.7.0
  nepali_date_picker: ^5.1.0 
  # qr_code_scanner:
  #   git:
  #     url: https://github.com/X-SLAYER/qr_code_scanner.git
  #     ref: flutter-beta
  eva_icons_flutter: ^3.1.0
  qr_flutter: ^4.0.0
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+3
  cached_network_image: ^3.2.0
  easy_localization: ^3.0.0
  hive_generator: ^1.1.3
  

#launcher icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/profile.png"

  cupertino_icons: ^1.0.2
  #for svgs
  flutter_svg: ^1.0.3
  #BLOC(State Management)
  flutter_bloc: ^8.0.1
  #dependency injection

  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/splash/
    - assets/images/logo/
    - assets/images/logo/drawer/
    - assets/l10n/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
